### ISSUE TITLE
CSV file is not support

### ISSUE THREAD

**Issue by sdkshn** [Maprunner/rg2#242]
oryantiring.info/routegadget

oe2010 csv export is not full support. In this site, event that is "denemee" had error. Runner times is not true. Why did I get this problem? Wrong CSV or anything else?

**Comment by Maprunner** [comment]
If at all possible I would suggest using IOF XML results files.

csv is a badly defined format. RG2 tries to work out what fields are where based on column names. If it fails it falls back to the [British Orienteering Federation csv format.] (http://www.britishorienteering.org.uk/images/uploaded/downloads/events_results_submission_file_specification.pdf)

If you send me your csv file I can see exactly what the problem is.

**Comment by sdkshn** [comment]
thanks i got it
