### ISSUE TITLE
turkish language support

### ISSUE THREAD

**Issue by sdkshn** [Maprunner/rg2#243]
![ekran alintisi](https://cloud.githubusercontent.com/assets/5912993/6389778/ca782f94-bdaf-11e4-93de-5adca1763ad0.PNG)

where can i fix this?

**Comment by Maprunner** [comment]
The problem is probably in the results file that you use to import the results. This needs to be in UTF-8 format.

Some systems claim to produce UTF-8 files but they are not real UTF-8. The most successful way of converting things that I have found is to use Notepad on Windows. Open the original file, and then chose File|Save As... There will be a dropdown at the bottom right labelled "Encoding". Select "UTF-8" and save the file. This should now import correctly.
