### ISSUE TITLE
PurplePen IOFv2 course file with comma decimal separator

### ISSUE THREAD

**Issue by MaBreaker** [Maprunner/rg2#269]
It seems that PurplePen in some cases takes decimal separator from local computer (regional setting) and uses that while prducing IOFv2 XML course file. So x,y coordination values can have either dot "." or comma "," as decimal separtor.

On the other hand RG2 xml import or xml engine does not take users local regional settings what causes failure on course loading. I do not know if this same issue exists with georeferenced XML IOF files as i do not have Ocad nor tested any.

This could be easily fixed by replacing X & Y decimal separator while inporting XML IOF course file.
 
courseparser.js

   getXYFromMapPosition : function (mapPosition) {
      return {x: parseFloat(mapPosition[0].getAttribute('x')<b>.replace(',', '.')</b>), y: parseFloat(mapPosition[0].getAttribute('y')<b>.replace(',', '.')</b>)};
    },

**Comment by Maprunner** [comment]
The IOF specification declares these as type [xsd:double] (http://books.xmlschemata.org/relaxng/ch19-77065.html)

"The decimal separator is always a point (.), and no thousands separator may be used."

So technically PurplePen is creating invalid XML files.

But I'll look at adding this in the next rg2 build since it's a simple change.
