### ISSUE TITLE
Issue with ?lang=fr in URL

### ISSUE THREAD

**Issue by MrHelga** [Maprunner/rg2#285]
in 1.2.0 when adding rg2/?lang=fr to the URL, the page remains empty except the banner line, and the buttons also don't work.
When selecting French in the configuration screen, everything works fine.

**Comment by Maprunner** [comment]
Problems are in formatting of the fr.txt file.

n'a needs to be n&apos;a

'Total time': Temps total, should be 'Total time': 'Temps total', (missing quotes).

d'ancrage needs to be d&apos;ancrage

comma missing at end of line before Autofit

One day I'll change the language files to be valid json like they should have been in the first place, but for now I'll update the fr.txt file

**Comment by Maprunner** [comment]
That probably didn't make much sense. n'a and d'ancrage need to have the ' replaced by & a p o s ; but that gets translated to ' every time you type it without the spaces. 

Anyway, corrected fr.txt file should be out in 1.2.1 later today.

**Comment by MrHelga** [comment]
Thank you, that makes sense. But on the page, they don't seem to be transformed to '.
![unbenannt](https://cloud.githubusercontent.com/assets/7961822/8508161/a6680334-2265-11e5-823d-268143c1faf0.PNG)

**Comment by Maprunner** [comment]
It turns out I'm doing things differently if you load a language at start-up or if you change after start-up, so I need to look at this a bit further.

But to get things to work properly for now using ?lang=fr you can change the translations to use double quotes with a single quote for the apostrophe. This is only needed for some of the translations which are displayed in a particular way.

'Left click to add/lock/unlock a handle': "Clic gauche pour ajouter/bloquer/débloquer un point d'ancrage",
'Right click to delete a handle': "Clic droit pour enlever un point d'ancrage",

**Comment by MrHelga** [comment]
Thanks Simon for this workaround which is a little better...
However there is no emergency; take your time to handle it properly in 
the next version.

**Comment by MrHelga** [comment]
Simon,

for your information, I encountered a similar problem when translating 
OCAD, and the same solution was used.  Therefore for the future and new 
strings to be added I can immediately use this work-around

Regards
Robert

**Comment by JamesErrington** [comment]
This issue still persists
