### ISSUE TITLE
New language handling v1.3.1 has some small bugs

### ISSUE THREAD

**Issue by MaBreaker** [Maprunner/rg2#334]
1) correctly pass selected language to setNewLangauge (rg2getjson.js)
getScript.done call returns script content into first variable so it can't be used to pass lang variable for sub routine.

```javascript
  function getNewLanguage(lang) {
    $.getScript(rg2Config.lang_url + lang + ".js")
      // .done does not pass variables like "lang" to it's sub routine
      .done(function () {
        // script sets rg2.dictionary to new language
        rg2.ui.setNewLanguage(lang);
      }).fail(function (jqxhr, settings, exception) {
        /*jslint unparam:true*/
        /* jshint unused:vars */
        reportJSONFail("Language request failed.");
      });
  }
```

2) select correct "start language" for options language dropdown list (config.js )
Options language drop down menu might be created before dictionary.code is properly set by dynamically loaded xx.js language script.

```javascript
  function setLanguageOptions() {
    // use English until we load something else
    dictionary = {};
    dictionary.code = 'en';
    if (rg2Config.start_language !== "en") {
      // temporarily set start language code for options language dropdown list
      dictionary.code = rg2Config.start_language;
      rg2.getNewLanguage(rg2Config.start_language);
    }
    // set available languages and set start language if requested
    rg2.createLanguageDropdown(rg2.config.languages);
  }
```

3) rg2.events used before initialization (rg2ui.js)
On "init" function start language file is loaded dynamically from xx.js by rg2.setLanguageOptions which also calls CreateEventMenu and rg2.events in it, but menu objects like "rg2.events" are not yet initialized at this point.

```javascript
    setNewLanguage : function (lang) {
      var eventid;
      if ($("#rg2-event-list").menu("instance") !== undefined) {
        $("#rg2-event-list").menu("destroy");
      }
      // non-english dictionary is already installed by script that has loaded
      if (lang === "en") {
        rg2.setDictionary({code: "en"});
      }
      // check if rg2.events is initialized
      if (rg2.events !== undefined) {
        this.createEventMenu();
        eventid = rg2.events.getActiveEventID();
        if (eventid !== null) {
          rg2.courses.removeAllFromDisplay();
          rg2.results.updateTrackDisplay(rg2.config.DISPLAY_ALL_COURSES, false);
          rg2.animation.resetAnimation();
          rg2.drawing.initialiseDrawing(rg2.events.hasResults(eventid));
          this.createCourseMenu();
          this.createResultMenu();
        }
      }
      $("#rg2-info-panel").tabs("refresh");
      rg2.redraw(false);
    },
```

**Comment by Maprunner** [comment]
1) I don't  know where you got this version of code, but lang is included as a parameter in the latest version. You need to sync against the master.

2) The languages dropdown is only created once on start-up, based on a hard-coded array in config.js. Not a brilliant design, but I need it this way to allow me to do something else. dictionary.code will always be set to "en" if nothing else has been requested, since this is done four lines earlier.

3) I agree that if you get a very quick response to a language request at start-up then things may not be fully initialised. That is why there is a test for rg2.events to be defined before resetting things. Is this really failing on your system or is it a theoretical issue. All tests I have done work correctly in this area.

**Comment by Maprunner** [comment]
Closing for now since there have been no other reports of problems.
