### ISSUE TITLE
Resizing and moving the Splits-window within the map-area

### ISSUE THREAD

**Issue by Xendras** [Maprunner/rg2#385]
Trying to resize or move the Splits-window within the map-area gives varying results at the moment. Once the window is made smaller by dragging the edges, making it larger requires moving the mouse outside of the map-area. Moving the window is also difficult within the map-area. It seems like the Splits-window does not receive proper info about relocation as long as the cursor is within the map-area.

This problem occurs with all browsers so far (Chrome, Firefox, Edge) as well as on three separate Windows-computers.

**Comment by Maprunner** [comment]
The splits handling may change a bit in the near future, but for now I've tidied it up a bit so at least the resize works sensibly. This means it becomes a modal dialog, but I don't think that is a problem since if you're looking at the splits then you don't really need to be able to do anything else. Should appear in the next release, which might be out later this weekend if things go OK.
