### ISSUE TITLE
GPS Upload POST size exceeded

### ISSUE THREAD

**Issue by dfgeorge** [Maprunner/rg2#393]
We have had a few instances where users GPS upload has failed due to the POST size on the server being exceeded (tracks over about 90mins). gpstrack.js creates a track with 1 second intervals which gets sent to the server. rg2api.php thins this to 3 second intervals before saving. 

Can the track be thinned to 3 second intervals before sending?

For a short term fix I have changed gpstrack.js->expandToOneSecondInterval to thin to 3 second intervals instead of 1.

**Comment by Maprunner** [comment]
We hit that problem at the Scottish 6-Day when creating the events. In the end I managed to remove some of the data being posted.

I'll have a look at trying to make GPS uploads smaller. The 3 second setting is purely because that is how the original Routegadget worked. Reducing from 1s to 3s will certainly reduce the Post size. The other way forward is to reformat the tracks to send deltas rather than absolutes. This is already done when sending tracks from the back end to the front end (see addTrack in [result.js](https://github.com/Maprunner/rg2/blob/master/js/result.js)), and saves a surprising amount.
