### ISSUE TITLE
error processing xml file

### ISSUE THREAD

**Issue by okvittem** [Maprunner/rg2#398]
Hi,
RG2 fails loading a result xml file. The file appears to be accepted by RG1, but not with RG2.
File is at http://www.ntnu.no/ntnu-bil/grupper/o/resultater/run201713.xml
It validates. Error messages attached.
![screenshot from 2017-09-15 11-29-33](https://user-images.githubusercontent.com/3093300/30476465-64db6496-9a0a-11e7-80f5-e2e655db7794.png)

**Comment by Maprunner** [comment]
[IOF  V2.0.3 DTD](http://www.soenniksen.dk/iof-datastandard/datastandard/current/IOFdata.dtd) defines Person as:

`<!ELEMENT Person (PersonName, PersonId, BirthDate?, Address*, Tele*, Nationality?, ModifyDate?)>`

I read this as meaning a Person **must** have a PersonName and a PersonId. Your results file doesn't have a PersonId defined, which is why you are getting this error.

But it's a simple enough change to check that PersonId does exist, so I'll put it in the next release.

Although the best solution may be to move to IOF XML V3 instead.
