### ISSUE TITLE
"View the list of events available" link is dead on BOK landing page

### ISSUE THREAD

**Issue by mpickering** [Maprunner/rg2#435]
Another configuration issue it seems.

Steps to reproduce

1. Visit: https://bok.routegadget.co.uk/
2. Click "View the list of events available"
3. Link is "https://www.bok.routegadget.co.uk/cgi-bin/reitti.cgi" which is incorrect

**Comment by Maprunner** [comment]
There are links like this all over the internet. I'm using .htaccess to redirect them, but it got a bit messed up in the week it took to migrate over 100 sites to https. Hopefully most things now sorted and anything else will get done when I can go back to a single top-level .htaccess rather than site-specific ones.
