### ISSUE TITLE
SyntaxError: Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by mrmoosehead** [Maprunner/rg2#457]
On https://www.aire.routegadget.co.uk/rg2/#196

Event request failed for event 196: SyntaxError: Unexpected token < in JSON at position 0

Guessing something in the configuration, or a mis-typed piece of information from the organisers?

**Comment by Maprunner** [comment]
It was caused by a very strange GPS route that started -;0;-0,0N0;-0,0N and kept going for a long time with a lot of 0s. Never seen this before and no idea what caused it.

For now I have deleted the route (result 50039, event 196) and things are OK. I'll add some extra error checking in the next release that should hide it, but finding what really caused it will be a bit harder.
